### PR TITLE
[ADD] crm_campaign_configuration: Campaign medium and source in res p…

### PR DESCRIPTION
**Pull request by Berezi**
…artner.

### CODE REVIEW

**Comment by Berezi** [comment]
@anajuaristi  @oihane @Daniel-CA @alfredoavanzosc review please.

**Comment by oihane** [comment]
Errores a corregir en el travis

FLAKE8
```
crm_campaign_configuration/__manifest__.py:14:13: E126 continuation line over-indented for hanging indent
```

Pylint
```
crm_campaign_configuration/views/res_partner_views.xml:8: [W7910(wrong-tabs-instead-of-spaces), ]  Use wrong tabs indentation instead of four spaces
crm_campaign_configuration/views/res_partner_views.xml:9: [W7910(wrong-tabs-instead-of-spaces), ]  Use wrong tabs indentation instead of four spaces
crm_campaign_configuration/views/res_partner_views.xml:10: [W7910(wrong-tabs-instead-of-spaces), ]  Use wrong tabs indentation instead of four spaces
```

**Comment by Berezi** [comment]
> Errores a corregir en el travis
> 
> FLAKE8
> 
> ```
> crm_campaign_configuration/__manifest__.py:14:13: E126 continuation line over-indented for hanging indent
> ```
> 
> Pylint
> 
> ```
> crm_campaign_configuration/views/res_partner_views.xml:8: [W7910(wrong-tabs-instead-of-spaces), ]  Use wrong tabs indentation instead of four spaces
> crm_campaign_configuration/views/res_partner_views.xml:9: [W7910(wrong-tabs-instead-of-spaces), ]  Use wrong tabs indentation instead of four spaces
> crm_campaign_configuration/views/res_partner_views.xml:10: [W7910(wrong-tabs-instead-of-spaces), ]  Use wrong tabs indentation instead of four spaces
> ```

Ados. Zuzendu det. Eskerrik asko.

**Comment by Berezi** [comment]
@anajuaristi @alfredoavanzosc @Daniel-CA @oihane review please.

**Review by alfredoavanzosc — APPROVED** [review]
:+1

**Review by anajuaristi — APPROVED** [review]

**Pull request merged**
